# Generated by Django 3.2.7 on 2021-09-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idregistro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_de_atencion', models.DateTimeField()),
                ('hora_final_de_atencion', models.DateTimeField()),
                ('empresa', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=30)),
                ('asunto', models.TextField(max_length=50)),
                ('respuesta', models.TextField(max_length=100)),
                ('fechaSolicitud', models.DateField()),
            ],
        ),
    ]
